import * as assert from 'assert';
import { describe, it } from 'mocha';
import { commonInputs } from '../../src';

describe('Common Input', () => {

  it("Invalid PSBT string", () => {
    
    const psbt = "Invalid";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, false);
  })
  it("PSBT string without single input", () => {
    
    const psbt = "cHNidP8BAFICAAAAAdBFTdfGHrTaikzvaTKAhExJuVcGOREES1pMk+a4GaJAAAAAAAD9////AQBlzR0AAAAAFgAUH07rdLvAqWwab5nTbBda6Xg0Q98AAAAAAAEAhQIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////BAK9AAD/////AgD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QAAAAABAR8A+QKVAAAAABYAFF3tbVuXHenOn6ebO8kHmbxhC5smAQhrAkcwRAIgZGDkxdepdIYHZEhITaZem41Rc/n99csk9RNxDrRDrKkCIE1MniWw0E5wyuVc1fhb7dkBsfwb2oGgGsNYMY8vgLFMASECEpeD7Cqlzuv2Yt1WI+NhvWXPNVQq+XzDTwk5RDEYs2UAAA==";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, true);
  })

  it("PSBT string with two common inputs", () => {
    
    const psbt = "cHNidP8BAJoCAAAAArQi7ef0E6AD6g9Bt3wyoscHkmxLEC5h3Ba8cmPSQ/4sAAAAAAD9////IqQqb5nXIPMqqsrPKqqM9EE/eX9gkZKUAy+fYMdXmkYAAAAAAP3///8CAMOd0AAAAAAWABTYHEIM3Jllq9ZySBvRa7ZnMvD3nQA4nBwAAAAAFgAU9qdaVArPWCM30vs6ld69/3eiKVsAAAAAAAEAcQIAAAABkA1Y8dByKH0mDyKUBe5ueP+y7aexxPG9XrK3MLrCnhAAAAAAAP3///8C8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1ADKmjsAAAAAFgAU+4gg817/oFQ5lUC4yoYEDY3apNUcAQAAAQEf8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1AEIawJHMEQCIAf/OZxXQcHWF8BCc8tMxfhmEWHJO2UFZiLvqBg1ZgR6AiAUDFs2ZlST1J/5ZZnYv2Kbqx7yS9FKrfu88OUY/ZtcjQEhAqfnB+Xj+3yW25hzjuemqOvocUU5UvzQcGVH4Ncr5QwzAAEAhQIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////BAK/AAD/////AgD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QAAAAABAR8A+QKVAAAAABYAFF3tbVuXHenOn6ebO8kHmbxhC5smAQhrAkcwRAIgLVf2JV2yYlmeOq5CtPTwrUVEcnwf/xLVGAKwXgZyIJwCIBGGdfzsO1QojarAayE6eO+kYb0ZsKgA6ENqb03D+zDVASECEpeD7Cqlzuv2Yt1WI+NhvWXPNVQq+XzDTwk5RDEYs2UAIgIC5yYXTUs6J3ysKAK7OJjEJN8GZtnt6zJbuknamKf8Md0Y/lEox1QAAIAAAACAAAAAgAAAAAAWAACAACICAg1+opX+0I0v1kK8mYBJpugWo6kLLjYKcvRF33NQGluUGP5RKMdUAACAAAAAgAAAAIAAAAAAFwAAgAA=";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, true);
  })
  
  it("Unprocessed PSBT string with single input and OP_RETURN output", () => {
    const psbt = "cHNidP8BAGwCAAAAAdBFTdfGHrTaikzvaTKAhExJuVcGOREES1pMk+a4GaJAAAAAAAD/////AmDjFgAAAAAAFgAUhLhXbj+oNR0OzS29IpNsRwYRfQsAAAAAAAAAABFqD0hlbGxvIE9wX1JldHVybgAAAAAAAAAA";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, true)
  })
  it("PSBT string with common input and a P2TR output", () => {
    const psbt = "cHNidP8BAO4CAAAAA7Qi7ef0E6AD6g9Bt3wyoscHkmxLEC5h3Ba8cmPSQ/4sAAAAAAD9////IqQqb5nXIPMqqsrPKqqM9EE/eX9gkZKUAy+fYMdXmkYAAAAAAP3////QRU3Xxh602opM72kygIRMSblXBjkRBEtaTJPmuBmiQAAAAAAA/f///wMAZc0dAAAAABYAFNb4eJD53mxJ8Ru5hiMCUxXal0g+APIFKgEAAAAWABQ71TsKSsxnTrRIXJ4LZAegWU1xlYB00hoAAAAAIlEgYLkNmG8lbNqEXf+I5magfYfc5xOelIeFrp5VLlc6D5IAAAAAAAEAcQIAAAABkA1Y8dByKH0mDyKUBe5ueP+y7aexxPG9XrK3MLrCnhAAAAAAAP3///8C8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1ADKmjsAAAAAFgAU+4gg817/oFQ5lUC4yoYEDY3apNUcAQAAAQEf8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1AEIawJHMEQCIAn4Zx97tsVKBSBcT2Up/nYh7KTP+PzaUgUE0BGbLwr0AiBbXZbmLeQJ8DV0lQfEpNcq97Nq6GDVuQhawuTtGkIWsgEhAqfnB+Xj+3yW25hzjuemqOvocUU5UvzQcGVH4Ncr5QwzAAEAhQIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////BAK/AAD/////AgD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QAAAAABAR8A+QKVAAAAABYAFF3tbVuXHenOn6ebO8kHmbxhC5smAQhrAkcwRAIgK6KU2mM+v6Xx0xzUfE0QdgYbtqnqogZRsLc8Cz7icCgCIC4PZgGfmVy1FO/0hKaXgCQFoTikchqzOu80opy3wzQgASECEpeD7Cqlzuv2Yt1WI+NhvWXPNVQq+XzDTwk5RDEYs2UAAQCFAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8EAr0AAP////8CAPkClQAAAAAWABRd7W1blx3pzp+nmzvJB5m8YQubJgAAAAAAAAAAJmokqiGp7eL2HD9x0d79P6mZ36NpU3VcaQaJeZlitIvr2DaXToz5AAAAAAEBHwD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYBCGsCRzBEAiBDJptx6SOcfCepoSaPkSOLamyz0+Gzynop/BmQ4chvCQIgBLXXBZO774FAtFsvQ6sDEhoCnl8oTW6zqbFIpHcshcoBIQISl4PsKqXO6/Zi3VYj42G9Zc81VCr5fMNPCTlEMRizZQAiAgNe1n09ToDdFAeJHse6qtq7G6me/5jCvX+UzTukdNhJ3Rj+USjHVAAAgAAAAIAAAACAAAAAAAEAAIAAIgICzi+OELLFTKFzjiiWsb6oa49LTSdDnTGC6HArlahkZPYY/lEox1QAAIAAAACAAAAAgAAAAAACAACAAAEFIClS2PXSyv19/puRG1eqk95e2QyNNoa8u2rO13qM6IqTIQcpUtj10sr9ff6bkRtXqpPeXtkMjTaGvLtqztd6jOiKkxkAxJnfzVYAAIABAACAAAAAgAAAAAABAAAAAA==";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, true)
  })
  it("Unprocessed PSBT string with common input and a P2TR output", () => {
    const psbt = "cHNidP8BAO4CAAAAA7Qi7ef0E6AD6g9Bt3wyoscHkmxLEC5h3Ba8cmPSQ/4sAAAAAAD9////IqQqb5nXIPMqqsrPKqqM9EE/eX9gkZKUAy+fYMdXmkYAAAAAAP3////QRU3Xxh602opM72kygIRMSblXBjkRBEtaTJPmuBmiQAAAAAAA/f///wMAZc0dAAAAABYAFNb4eJD53mxJ8Ru5hiMCUxXal0g+APIFKgEAAAAWABQ71TsKSsxnTrRIXJ4LZAegWU1xlYB00hoAAAAAIlEgYLkNmG8lbNqEXf+I5magfYfc5xOelIeFrp5VLlc6D5IAAAAAAAAAAAAAAA==";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, false)
  })
  it("PSBT string with uncommon inputs", () => {
    const psbt = "cHNidP8BAP0BAQIAAAADtCLt5/QToAPqD0G3fDKixweSbEsQLmHcFrxyY9JD/iwAAAAAAP3///8ipCpvmdcg8yqqys8qqoz0QT95f2CRkpQDL59gx1eaRgAAAAAA/f///9BFTdfGHrTaikzvaTKAhExJuVcGOREES1pMk+a4GaJAAAAAAAD9////BIA+bVYAAAAAFgAUlF/Upsmtavfz4ZtUXef7y4Sef0IA+QKVAAAAABYAFNb4eJD53mxJ8Ru5hiMCUxXal0g+AJQ1dwAAAAAWABQ71TsKSsxnTrRIXJ4LZAegWU1xlYB00hoAAAAAFgAUDE5OT6fMn7XJePFNLaEaTD4uvHYAAAAAAAEAcQIAAAABkA1Y8dByKH0mDyKUBe5ueP+y7aexxPG9XrK3MLrCnhAAAAAAAP3///8C8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1ADKmjsAAAAAFgAU+4gg817/oFQ5lUC4yoYEDY3apNUcAQAAAQEf8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1AEIawJHMEQCIH/eWaATaO0+SZxCDJEl48t5UaUeQzCK2N89qiYq4SqmAiAI2yk1AToli7ZW6YH9d1appR8v6V3QV85zdRPliGDUTwEhAqfnB+Xj+3yW25hzjuemqOvocUU5UvzQcGVH4Ncr5QwzAAEAhQIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////BAK/AAD/////AgD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QAAAAABAR8A+QKVAAAAABYAFF3tbVuXHenOn6ebO8kHmbxhC5smAQhrAkcwRAIgLQXLkzepwGFI8ScmPrmjHeYZtGfXamu8xLFvHHVjHQICICV/LqYVH/Dj/WU4rPcNlRAUHKLZCa0NcEKzGz1SSuQ4ASECEpeD7Cqlzuv2Yt1WI+NhvWXPNVQq+XzDTwk5RDEYs2UAAQCFAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8EAr0AAP////8CAPkClQAAAAAWABRd7W1blx3pzp+nmzvJB5m8YQubJgAAAAAAAAAAJmokqiGp7eL2HD9x0d79P6mZ36NpU3VcaQaJeZlitIvr2DaXToz5AAAAAAEBHwD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYBCGsCRzBEAiANydthAH4aNaWAY4Dr+M3dMu3u+fo3avIu1gv15iW+wgIgCB9D6VVQuBzu+ydG2vgEvDrGoUhZimBPyJZOyexGTG4BIQISl4PsKqXO6/Zi3VYj42G9Zc81VCr5fMNPCTlEMRizZQAiAgNKIArur4qKSOY2WIpYiH/Q1T+Ar8IB8M1RAx/gPMP30Bj+USjHVAAAgAAAAIAAAACAAAAAAAQAAIAAIgIDXtZ9PU6A3RQHiR7Huqrauxupnv+Ywr1/lM07pHTYSd0Y/lEox1QAAIAAAACAAAAAgAAAAAABAACAACICAs4vjhCyxUyhc44olrG+qGuPS00nQ50xguhwK5WoZGT2GP5RKMdUAACAAAAAgAAAAIAAAAAAAgAAgAAiAgOw9VZl12mlDByPmst9r+rQs7/yg5if9S28s7pdxK7Schj+USjHVAAAgAAAAIAAAACAAAAAAAUAAIAA";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, false)
  })
  it("PSBT string with common inputs", () => {
    const psbt = "cHNidP8BAOICAAAAA7Qi7ef0E6AD6g9Bt3wyoscHkmxLEC5h3Ba8cmPSQ/4sAAAAAAD9////IqQqb5nXIPMqqsrPKqqM9EE/eX9gkZKUAy+fYMdXmkYAAAAAAP3////QRU3Xxh602opM72kygIRMSblXBjkRBEtaTJPmuBmiQAAAAAAA/f///wMAZc0dAAAAABYAFPBDHh7uWqcHO721QZpXEuVoTBwOAPIFKgEAAAAWABSV05b1lMkxc+nqd+uPSUILVwYeHYB00hoAAAAAFgAUSYF1d44xnLRVdC6NnlHL02D8CFIAAAAAAAEAcQIAAAABkA1Y8dByKH0mDyKUBe5ueP+y7aexxPG9XrK3MLrCnhAAAAAAAP3///8C8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1ADKmjsAAAAAFgAU+4gg817/oFQ5lUC4yoYEDY3apNUcAQAAAQEf8C9oWQAAAAAWABTyU5PRkDq8RbcBO4xPAw3fzm/j1AEIawJHMEQCIBWdIWlH77JvRrC5N19jGxWtqnFAG+P8EGSyrEbCxbm6AiAGB2hVmaC6sp+HF8+sGSsgtA7492vAY4i3OJbZ1ud2rwEhAqfnB+Xj+3yW25hzjuemqOvocUU5UvzQcGVH4Ncr5QwzAAEAhQIAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////BAK/AAD/////AgD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAAAAAAAAAACZqJKohqe3i9hw/cdHe/T+pmd+jaVN1XGkGiXmZYrSL69g2l06M+QAAAAABAR8A+QKVAAAAABYAFF3tbVuXHenOn6ebO8kHmbxhC5smAQhrAkcwRAIgQZb6cvmz+zN2XKi0uTiDGA/h54Fwmq7Kgl79+OaHrOcCIGTn1V7atHIbSftBVk0JSjXbIO4lKGViV+/w2o0LbogTASECEpeD7Cqlzuv2Yt1WI+NhvWXPNVQq+XzDTwk5RDEYs2UAAQCFAgAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////8EAr0AAP////8CAPkClQAAAAAWABRd7W1blx3pzp+nmzvJB5m8YQubJgAAAAAAAAAAJmokqiGp7eL2HD9x0d79P6mZ36NpU3VcaQaJeZlitIvr2DaXToz5AAAAAAEBHwD5ApUAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYBCGsCRzBEAiAsbL5J8BmYU7xiXB4ugXwSHHDNBHqHO/yPDLW+iB3IJQIgbHfGNYtsGsZLhOvL7zyLdOvbttbrAhqi/gtKRQG5WhQBIQISl4PsKqXO6/Zi3VYj42G9Zc81VCr5fMNPCTlEMRizZQAiAgMjkEGAFU7t2ZpZU7QYhUnYLLwl2bKoXI3GUHFBrVytkRj+USjHVAAAgAAAAIAAAACAAAAAABgAAIAAIgIDnk5kTZxabqSy0Df2AIBzdMm0NvKzWE0quAqQ9WQyKXMY/lEox1QAAIAAAACAAAAAgAAAAAAZAACAACICA93qRxGbq7sngAu30XKdzWme16stQ7Aa9gWZJmhxP6cMGP5RKMdUAACAAAAAgAAAAIAAAAAAGgAAgAA=";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, true)
  })
  it("Unprocessed PSBT string with uncommon inputs", () => {
    const psbt = "cHNidP8BAP0BAQIAAAADtCLt5/QToAPqD0G3fDKixweSbEsQLmHcFrxyY9JD/iwAAAAAAP3///8ipCpvmdcg8yqqys8qqoz0QT95f2CRkpQDL59gx1eaRgAAAAAA/f///9BFTdfGHrTaikzvaTKAhExJuVcGOREES1pMk+a4GaJAAAAAAAD9////BIAICJIAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAL2hZAAAAABYAFNb4eJD53mxJ8Ru5hiMCUxXal0g+AJQ1dwAAAAAWABQ71TsKSsxnTrRIXJ4LZAegWU1xlYB00hoAAAAAFgAUZCdS7uN8HbzN97QP3Z9jsGwxj0YAAAAAAAAAAAAAAAA=";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, false)
  })
  it("Unprocessed PSBT string with common inputs", () => {
    const psbt = "cHNidP8BAP0BAQIAAAADtCLt5/QToAPqD0G3fDKixweSbEsQLmHcFrxyY9JD/iwAAAAAAP3///8ipCpvmdcg8yqqys8qqoz0QT95f2CRkpQDL59gx1eaRgAAAAAA/f///9BFTdfGHrTaikzvaTKAhExJuVcGOREES1pMk+a4GaJAAAAAAAD9////BAAvaFkAAAAAFgAUXe1tW5cd6c6fp5s7yQeZvGELmyYAZc0dAAAAABYAFNb4eJD53mxJ8Ru5hiMCUxXal0g+APIFKgEAAAAWABQ71TsKSsxnTrRIXJ4LZAegWU1xlYB00hoAAAAAFgAU5gRNSF4O3n70Nx5G4ifopbs6PVIAAAAAAAAAAAAAAAA=";

    const result = commonInputs(psbt);
    assert.deepStrictEqual(result, false)
  })
})